package kraii.ir

import kraii.KraiiPluginKey
import kraii.api.Scoped
import kraii.closeName
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.builtins.StandardNames
import org.jetbrains.kotlin.descriptors.DescriptorVisibilities
import org.jetbrains.kotlin.ir.IrElement
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.UNDEFINED_OFFSET
import org.jetbrains.kotlin.ir.builders.IrBuilderWithScope
import org.jetbrains.kotlin.ir.builders.declarations.buildFun
import org.jetbrains.kotlin.ir.builders.irBlock
import org.jetbrains.kotlin.ir.builders.irCall
import org.jetbrains.kotlin.ir.builders.irEqualsNull
import org.jetbrains.kotlin.ir.builders.irGet
import org.jetbrains.kotlin.ir.builders.irIfThen
import org.jetbrains.kotlin.ir.builders.irIfThenElse
import org.jetbrains.kotlin.ir.builders.irNotEquals
import org.jetbrains.kotlin.ir.builders.irNull
import org.jetbrains.kotlin.ir.builders.irSet
import org.jetbrains.kotlin.ir.builders.irTry
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrDeclaration
import org.jetbrains.kotlin.ir.declarations.IrDeclarationOrigin
import org.jetbrains.kotlin.ir.declarations.IrFile
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrParameterKind
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.createBlockBody
import org.jetbrains.kotlin.ir.declarations.impl.IrVariableImpl
import org.jetbrains.kotlin.ir.expressions.IrBlockBody
import org.jetbrains.kotlin.ir.expressions.IrStatementOrigin
import org.jetbrains.kotlin.ir.expressions.impl.IrCatchImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrFunctionExpressionImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrThrowImpl
import org.jetbrains.kotlin.ir.symbols.IrSimpleFunctionSymbol
import org.jetbrains.kotlin.ir.symbols.impl.IrValueParameterSymbolImpl
import org.jetbrains.kotlin.ir.symbols.impl.IrVariableSymbolImpl
import org.jetbrains.kotlin.ir.types.IrType
import org.jetbrains.kotlin.ir.types.classFqName
import org.jetbrains.kotlin.ir.types.getClass
import org.jetbrains.kotlin.ir.types.makeNullable
import org.jetbrains.kotlin.ir.types.typeOrNull
import org.jetbrains.kotlin.ir.types.typeWith
import org.jetbrains.kotlin.ir.util.functions
import org.jetbrains.kotlin.ir.util.kotlinFqName
import org.jetbrains.kotlin.ir.util.patchDeclarationParents
import org.jetbrains.kotlin.ir.util.properties
import org.jetbrains.kotlin.ir.visitors.IrVisitorVoid
import org.jetbrains.kotlin.ir.visitors.acceptChildrenVoid
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name

/**
 * Generates the body of the [AutoCloseable.close] method.
 * Closes all properties annotated with @Scoped in reverse declaration order.
 */
class KraiiCloseMethodBodyGenerator(
  private val pluginContext: IrPluginContext,
) : IrVisitorVoid() {

  private val irFactory = pluginContext.irFactory
  private val irBuiltIns = pluginContext.irBuiltIns

  override fun visitElement(element: IrElement) {
    when (element) {
      is IrDeclaration,
      is IrFile,
      is IrModuleFragment,
      -> element.acceptChildrenVoid(this)

      else -> {}
    }
  }

  override fun visitSimpleFunction(declaration: IrSimpleFunction) {
    if (declaration.name != closeName) return

    val irClass = declaration.parent as? IrClass ?: return

    val origin = declaration.origin
    val isGeneratedByUs =
      origin is IrDeclarationOrigin.GeneratedByPlugin &&
        origin.pluginKey == KraiiPluginKey

    if (isGeneratedByUs) {
      // Generated by our plugin: create the full body
      declaration.body =
        generateCloseBody(
          declaration,
          irClass,
          existingStatements = emptyList<IrStatement>(),
        )
    } else {
      // Existing user-defined method: append cleanup code to existing body
      val existingBody = declaration.body as? IrBlockBody ?: return
      declaration.body =
        generateCloseBody(
          declaration,
          irClass,
          existingStatements = existingBody.statements,
        )
    }
  }

  private fun generateCloseBody(
    closeFunction: IrSimpleFunction,
    irClass: IrClass,
    existingStatements: List<IrStatement>,
  ): IrBlockBody {
    val builder = DeclarationIrBuilder(pluginContext, closeFunction.symbol)
    val statements = mutableListOf<IrStatement>()

    val propertiesToClose = irClass.properties
      .filter { it.isAnnotatedWith(Scoped::class) }
      .toList()
      .reversed()

    val thisReceiver = closeFunction.dispatchReceiverParameter!!

    val closeStatements = mutableListOf<IrStatement>()

    for (property in propertiesToClose) {
      val propertyType = property.type

      if (propertyType.implements(AutoCloseable::class)) {
        // Direct AutoCloseable: call property.close()
        val getter = property.getter ?: continue
        val closeMethod = propertyType.functionByName("close") ?: continue

        val getProperty = builder
          .irCall(
            getter,
            origin = IrStatementOrigin.GET_PROPERTY,
          ).apply {
            dispatchReceiver = builder.irGet(thisReceiver)
          }

        val callClose = builder.irCall(closeMethod).apply {
          dispatchReceiver = getProperty
        }

        closeStatements.add(callClose)
      } else if (propertyType.implements(Iterable::class)) {
        // Iterable<AutoCloseable>: call property.reversed().forEach { it.close() }
        val getter = property.getter ?: continue
        val elementType = propertyType.arguments.first().typeOrNull ?: continue

        val getProperty = builder
          .irCall(
            getter,
            origin = IrStatementOrigin.GET_PROPERTY,
          ).apply {
            dispatchReceiver = builder.irGet(thisReceiver)
          }

        // property.reversed()
        val reversedCall = builder.irCall(iterableReversedSymbol).apply {
          arguments[0] =
            getProperty // Extension receiver at index 0 for top-level extension
        }

        // Create lambda: { it: T -> it.close() }
        val lambda = builder.createCloseLambda(elementType)

        // .forEach(lambda)
        val forEachCall = builder.irCall(iterableForEachSymbol).apply {
          arguments[0] = reversedCall // Extension receiver at index 0
          typeArguments[0] = elementType
          arguments[1] = IrFunctionExpressionImpl(
            // Lambda is the second argument
            startOffset = UNDEFINED_OFFSET,
            endOffset = UNDEFINED_OFFSET,
            type = createFunctionType(elementType),
            function = lambda,
            origin = IrStatementOrigin.LAMBDA,
          ).also {
            lambda.patchDeclarationParents(closeFunction)
          }
        }

        closeStatements.add(forEachCall)
      }
    }

    val hasExistingBody = existingStatements.isNotEmpty()
    val needsExceptionAggregation =
      closeStatements.size > 1 ||
        (hasExistingBody && closeStatements.isNotEmpty())

    if (needsExceptionAggregation) {
      // Wrap existing body (if any) and close calls in try-catch
      // with exception aggregation (addSuppressed). This ensures
      // that if the user body throws, cleanup still runs and close
      // exceptions are suppressed rather than replacing the
      // original.
      val allStatements = mutableListOf<IrStatement>()
      if (hasExistingBody) {
        allStatements.add(
          builder.irBlock {
            existingStatements.forEach { +it }
          },
        )
      }
      allStatements.addAll(closeStatements)
      statements.addAll(
        builder.wrapWithExceptionAggregation(allStatements, closeFunction),
      )
    } else {
      // No existing body with at most one close call: no need for
      // exception aggregation.
      statements.addAll(existingStatements)
      statements.addAll(closeStatements)
    }

    return irFactory.createBlockBody(
      UNDEFINED_OFFSET,
      UNDEFINED_OFFSET,
      statements,
    )
  }

  /**
   * Wraps close statements in try-catch blocks with exception aggregation.
   *
   * Generates:
   * ```
   * var exception: Throwable? = null
   * try { close1() } catch (e) { exception = e }
   * try { close2() } catch (e) { if (exception == null) exception = e else exception.addSuppressed(e) }
   * ...
   * if (exception != null) throw exception
   * ```
   */
  private fun IrBuilderWithScope.wrapWithExceptionAggregation(
    closeStatements: List<IrStatement>,
    closeFunction: IrSimpleFunction,
  ): List<IrStatement> {
    val result = mutableListOf<IrStatement>()

    // var exception: Throwable? = null
    val exceptionVar = IrVariableImpl(
      UNDEFINED_OFFSET,
      UNDEFINED_OFFSET,
      IrDeclarationOrigin.DEFINED,
      IrVariableSymbolImpl(),
      Name.identifier("\$closeException"),
      irBuiltIns.throwableType.makeNullable(),
      isVar = true,
      isConst = false,
      isLateinit = false,
    ).apply {
      initializer = irNull()
      parent = closeFunction
    }
    result.add(exceptionVar)

    val addSuppressedMethod = irBuiltIns.throwableType
      .getClass()
      ?.functions
      ?.firstOrNull { it.name == Name.identifier("addSuppressed") }

    for (closeStatement in closeStatements) {
      val catchParam = IrVariableImpl(
        UNDEFINED_OFFSET,
        UNDEFINED_OFFSET,
        IrDeclarationOrigin.CATCH_PARAMETER,
        IrVariableSymbolImpl(),
        Name.identifier("e"),
        irBuiltIns.throwableType,
        isVar = false,
        isConst = false,
        isLateinit = false,
      ).apply {
        parent = closeFunction
      }

      val catchBody = if (addSuppressedMethod != null) {
        // if (exception == null) exception = e
        // else exception!!.addSuppressed(e)
        irIfThenElse(
          type = irBuiltIns.unitType,
          condition = irEqualsNull(irGet(exceptionVar)),
          thenPart = irSet(exceptionVar, irGet(catchParam)),
          elsePart = irCall(addSuppressedMethod).apply {
            dispatchReceiver = irGet(exceptionVar)
            arguments[1] = irGet(catchParam)
          },
        )
      } else {
        // Fallback: just replace exception
        irSet(exceptionVar, irGet(catchParam))
      }

      val catch = IrCatchImpl(
        startOffset = UNDEFINED_OFFSET,
        endOffset = UNDEFINED_OFFSET,
        catchParameter = catchParam,
        result = catchBody,
      )

      val tryCatch = irTry(
        type = irBuiltIns.unitType,
        tryResult = irBlock { +closeStatement },
        catches = listOf(catch),
        finallyExpression = null,
      )

      result.add(tryCatch)
    }

    // if (exception != null) throw exception
    val rethrow = irIfThen(
      irBuiltIns.unitType,
      irNotEquals(irGet(exceptionVar), irNull()),
      IrThrowImpl(
        UNDEFINED_OFFSET,
        UNDEFINED_OFFSET,
        irBuiltIns.nothingType,
        irGet(exceptionVar),
      ),
    )

    result.add(rethrow)

    return result
  }

  @Suppress("DEPRECATION")
  private fun IrBuilderWithScope.createCloseLambda(
    elementType: IrType,
  ): IrSimpleFunction {
    val closeMethod = elementType.functionByName("close")
      ?: error("close() method not found on $elementType")

    return irFactory
      .buildFun {
        name = Name.special("<anonymous>")
        returnType = irBuiltIns.unitType
        origin = IrDeclarationOrigin.LOCAL_FUNCTION_FOR_LAMBDA
        visibility = DescriptorVisibilities.LOCAL
      }.apply {
        val itParam = irFactory
          .createValueParameter(
            startOffset = UNDEFINED_OFFSET,
            endOffset = UNDEFINED_OFFSET,
            origin = IrDeclarationOrigin.DEFINED,
            kind = IrParameterKind.Regular,
            name = Name.identifier("it"),
            type = elementType,
            isAssignable = false,
            symbol = IrValueParameterSymbolImpl(),
            varargElementType = null,
            isCrossinline = false,
            isNoinline = false,
            isHidden = false,
          ).also { it.parent = this }

        parameters = listOf(itParam)

        body = irFactory.createBlockBody(
          UNDEFINED_OFFSET,
          UNDEFINED_OFFSET,
          listOf(
            irCall(closeMethod).apply {
              dispatchReceiver = irGet(itParam)
            },
          ),
        )
      }
  }

  private fun createFunctionType(paramType: IrType): IrType {
    val functionClass =
      pluginContext
        .finderForBuiltins()
        .findClass(StandardNames.getFunctionClassId(1))
        ?: error("Cannot find Function1 class")
    return functionClass.typeWith(paramType, irBuiltIns.unitType)
  }

  private val iterableForEachSymbol: IrSimpleFunctionSymbol by lazy {
    pluginContext
      .finderForBuiltins()
      .findFunctions(
        CallableId(FqName("kotlin.collections"), Name.identifier("forEach")),
      ).single {
        it.owner.parameters
          .find { p ->
            p.kind ==
              IrParameterKind.ExtensionReceiver
          }?.type
          ?.classFqName == irBuiltIns.iterableClass.owner.kotlinFqName
      }
  }

  private val iterableReversedSymbol: IrSimpleFunctionSymbol by lazy {
    pluginContext
      .finderForBuiltins()
      .findFunctions(
        CallableId(FqName("kotlin.collections"), Name.identifier("reversed")),
      ).single {
        it.owner.parameters
          .find { p ->
            p.kind ==
              IrParameterKind.ExtensionReceiver
          }?.type
          ?.classFqName == irBuiltIns.iterableClass.owner.kotlinFqName
      }
  }
}
