package kraii.ir

import kraii.KraiiPluginKey
import kraii.api.Scoped
import kraii.closeName
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.ir.IrElement
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.UNDEFINED_OFFSET
import org.jetbrains.kotlin.ir.builders.IrBuilderWithScope
import org.jetbrains.kotlin.ir.builders.irBlock
import org.jetbrains.kotlin.ir.builders.irCall
import org.jetbrains.kotlin.ir.builders.irEqualsNull
import org.jetbrains.kotlin.ir.builders.irGet
import org.jetbrains.kotlin.ir.builders.irIfThen
import org.jetbrains.kotlin.ir.builders.irIfThenElse
import org.jetbrains.kotlin.ir.builders.irNotEquals
import org.jetbrains.kotlin.ir.builders.irNull
import org.jetbrains.kotlin.ir.builders.irSet
import org.jetbrains.kotlin.ir.builders.irTry
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrDeclaration
import org.jetbrains.kotlin.ir.declarations.IrDeclarationOrigin
import org.jetbrains.kotlin.ir.declarations.IrFile
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrProperty
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueParameter
import org.jetbrains.kotlin.ir.declarations.createBlockBody
import org.jetbrains.kotlin.ir.declarations.impl.IrVariableImpl
import org.jetbrains.kotlin.ir.expressions.IrBlockBody
import org.jetbrains.kotlin.ir.expressions.impl.IrCatchImpl
import org.jetbrains.kotlin.ir.symbols.impl.IrVariableSymbolImpl
import org.jetbrains.kotlin.ir.types.getClass
import org.jetbrains.kotlin.ir.types.makeNullable
import org.jetbrains.kotlin.ir.util.functions
import org.jetbrains.kotlin.ir.util.properties
import org.jetbrains.kotlin.ir.visitors.IrVisitorVoid
import org.jetbrains.kotlin.ir.visitors.acceptChildrenVoid
import org.jetbrains.kotlin.name.Name

/**
 * Generates the body of the `close()` method for classes with @Scoped
 * properties.
 *
 * This visitor finds `close()` methods (either generated by our FIR extension
 * or user-defined) and fills in or appends the cleanup code that closes
 * all @Scoped properties in reverse declaration order (LIFO).
 *
 * Two property types are supported:
 * - `AutoCloseable`:
 *   generates `property.close()`
 * - `Iterable<AutoCloseable>`:
 *   generates an exception-safe loop that closes each element individually,
 *   aggregating exceptions via `addSuppressed()`
 *
 * When there are multiple close calls (or a user body + close calls), all
 * operations are wrapped with exception aggregation so that a failing close
 * doesn't prevent subsequent closes from running. Exceptions are collected via
 * `addSuppressed()`.
 *
 * Example — given:
 * ```
 * class MyResource : AutoCloseable {
 *   @Scoped val a = ResourceA()
 *   @Scoped val b = ResourceB()
 * }
 * ```
 *
 * This generates a close() body equivalent to:
 * ```
 * class MyResource : AutoCloseable {
 *   @Scoped val a = ResourceA()
 *   @Scoped val b = ResourceB()
 *
 *   override fun close() {
 *     var exception: Throwable? = null
 *     try { b.close() } catch (e: Throwable) { exception = e }
 *     try { a.close() } catch (e: Throwable) {
 *       if (exception == null) exception = e
 *       else exception.addSuppressed(e)
 *     }
 *     if (exception != null) throw exception
 *   }
 * }
 * ```
 */
class KraiiCloseMethodBodyGenerator(
  private val pluginContext: IrPluginContext,
) : IrVisitorVoid() {

  private val irFactory = pluginContext.irFactory
  private val irBuiltIns = pluginContext.irBuiltIns

  override fun visitElement(element: IrElement) {
    when (element) {
      is IrDeclaration,
      is IrFile,
      is IrModuleFragment,
      -> element.acceptChildrenVoid(this)

      else -> {}
    }
  }

  /**
   * Intercepts close() method declarations to fill in their bodies.
   *
   * Handles two cases:
   * - Plugin-generated close(): creates the entire body from scratch.
   * - User-defined close(): preserves the existing body and appends cleanup
   *   code after it, so the user's logic runs first.
   */
  override fun visitSimpleFunction(declaration: IrSimpleFunction) {
    if (declaration.name != closeName) return

    val irClass = declaration.parent as? IrClass ?: return

    val origin = declaration.origin
    val isGeneratedByUs =
      origin is IrDeclarationOrigin.GeneratedByPlugin &&
        origin.pluginKey == KraiiPluginKey

    if (isGeneratedByUs) {
      // Plugin-generated close(): create the full body.
      declaration.body =
        generateCloseBody(
          declaration,
          irClass,
          existingStatements = emptyList(),
        )
    } else {
      // User-defined close(): append cleanup after existing body.
      val existingBody = declaration.body as? IrBlockBody
        ?: error(
          "User-defined close() in ${irClass.name} has an" +
            " unsupported body type (expected IrBlockBody," +
            " got ${declaration.body?.let {
              it::class.simpleName
            }})",
        )
      declaration.body =
        generateCloseBody(
          declaration,
          irClass,
          existingStatements = existingBody.statements,
        )
    }
  }

  /**
   * Generates the full close() method body.
   *
   * Steps:
   * 1. Collect @Scoped properties in reverse declaration order (LIFO).
   * 2. Build a close statement for each property (`AutoCloseable` or
   *    `Iterable`).
   * 3. Assemble the final body. Wrap in exception aggregation if multiple
   *    operations exist, otherwise emit close calls directly.
   */
  private fun generateCloseBody(
    closeFunction: IrSimpleFunction,
    irClass: IrClass,
    existingStatements: List<IrStatement>,
  ): IrBlockBody {
    val builder = DeclarationIrBuilder(pluginContext, closeFunction.symbol)
    val thisReceiver = closeFunction.dispatchReceiverParameter!!

    // Step 1: Collect @Scoped properties in reverse declaration order.
    // LIFO order ensures resources are closed in the opposite order they
    // were opened, which is the expected RAII cleanup order.
    val propertiesToClose = irClass.properties
      .filter { it.isAnnotatedWith(Scoped::class) }
      .toList()
      .reversed()

    // Step 2: Build a close IR statement for each @Scoped property.
    val closeStatements = propertiesToClose.map { property ->
      builder.buildCloseStatementForProperty(
        property,
        thisReceiver,
        closeFunction,
      )
    }

    // Step 3: Assemble the final body, deciding whether exception
    // aggregation is needed.
    val statements = assembleCloseBody(
      builder,
      existingStatements,
      closeStatements,
      closeFunction,
    )

    return irFactory.createBlockBody(
      startOffset = UNDEFINED_OFFSET,
      endOffset = UNDEFINED_OFFSET,
      statements = statements,
    )
  }

  /**
   * Builds the close statement for a single @Scoped property, dispatching
   * based on whether the property is a direct `AutoCloseable` or an
   * `Iterable<AutoCloseable>`.
   */
  private fun IrBuilderWithScope.buildCloseStatementForProperty(
    property: IrProperty,
    thisReceiver: IrValueParameter,
    closeFunction: IrSimpleFunction,
  ): IrStatement =
    when {
      property.type.implements(AutoCloseable::class) ->
        // property.close()
        buildCloseAutoCloseable(property, thisReceiver)

      property.type.implements(Iterable::class) ->
        // property.reversed().forEach { it.close() }
        buildCloseIterable(
          pluginContext = pluginContext,
          property = property,
          receiver = thisReceiver,
        )

      else -> error(
        "@Scoped property ${property.name} is neither AutoCloseable nor" +
          " Iterable<AutoCloseable>",
      )
    }

  /**
   * Assembles the final list of statements for the close() body.
   *
   * Decides between two strategies:
   * - **With exception aggregation**: When there are multiple close operations
   *   (or a user body + close operations). Each operation is wrapped in its own
   *   try-catch and exceptions are collected via addSuppressed().
   * - **Without exception aggregation**: When there's at most one close
   *   operation and no user body. No wrapping overhead needed.
   */
  private fun assembleCloseBody(
    builder: DeclarationIrBuilder,
    existingStatements: List<IrStatement>,
    closeStatements: List<IrStatement>,
    closeFunction: IrSimpleFunction,
  ): List<IrStatement> {
    val hasExistingBody = existingStatements.isNotEmpty()
    val needsExceptionAggregation =
      closeStatements.size > 1 ||
        (hasExistingBody && closeStatements.isNotEmpty())

    if (!needsExceptionAggregation) {
      // Simple case: at most one close call, no user body to protect.
      // Emit statements directly without try-catch wrapping.
      return existingStatements + closeStatements
    }

    // Complex case: multiple operations that could each throw.
    // Wrap everything in try-catch with exception aggregation so that
    // a failing close doesn't prevent subsequent closes from running.
    //
    // The user body (if present) is treated as the first operation,
    // ensuring that if the user body throws, all @Scoped properties
    // are still closed and the user's exception is propagated with
    // close exceptions attached via addSuppressed().
    val allOperations = mutableListOf<IrStatement>()
    if (hasExistingBody) {
      allOperations.add(
        builder.irBlock { existingStatements.forEach { +it } },
      )
    }
    allOperations.addAll(closeStatements)

    return builder.wrapWithExceptionAggregation(allOperations, closeFunction)
  }

  /**
   * Wraps multiple close operations in individual try-catch blocks with
   * exception aggregation via `addSuppressed()`.
   *
   * This ensures that ALL close operations run even if some throw exceptions.
   * The first exception is stored, and subsequent exceptions are attached to it
   * via `addSuppressed()`. After all operations complete, the aggregated
   * exception (if any) is rethrown.
   *
   * Generates:
   * ```
   * var $closeException: Throwable? = null
   * try { operation1() } catch (e: Throwable) { $closeException = e }
   * try { operation2() } catch (e: Throwable) {
   *   if ($closeException == null) $closeException = e
   *   else $closeException!!.addSuppressed(e)
   * }
   * ...
   * if ($closeException != null) throw $closeException
   * ```
   */
  private fun IrBuilderWithScope.wrapWithExceptionAggregation(
    operations: List<IrStatement>,
    closeFunction: IrSimpleFunction,
  ): List<IrStatement> {
    val result = mutableListOf<IrStatement>()

    // var $closeException: Throwable? = null
    val exceptionVar = IrVariableImpl(
      startOffset = UNDEFINED_OFFSET,
      endOffset = UNDEFINED_OFFSET,
      origin = IrDeclarationOrigin.DEFINED,
      symbol = IrVariableSymbolImpl(),
      name = Name.identifier($$"$closeException"),
      type = irBuiltIns.throwableType.makeNullable(),
      isVar = true,
      isConst = false,
      isLateinit = false,
    ).apply {
      initializer = irNull()
      parent = closeFunction
    }
    result.add(exceptionVar)

    val addSuppressedMethod = irBuiltIns.throwableType
      .getClass()
      ?.functions
      ?.firstOrNull { it.name == Name.identifier("addSuppressed") }
      ?: error(
        "Throwable.addSuppressed() not found. " +
          "kraii requires a JVM target that provides this method.",
      )

    // Wrap each operation in: try { operation() } catch (e: Throwable) { ... }
    for (operation in operations) {
      val catchParam = buildCatchParameter(irBuiltIns.throwableType).apply {
        parent = closeFunction
      }

      // try { operation() } catch (e: Throwable) { <aggregate exception> }
      result.add(
        irTry(
          type = irBuiltIns.unitType,
          tryResult = irBlock { +operation },
          catches = listOf(
            IrCatchImpl(
              startOffset = UNDEFINED_OFFSET,
              endOffset = UNDEFINED_OFFSET,
              catchParameter = catchParam,
              // if ($closeException == null) $closeException = e
              // else $closeException!!.addSuppressed(e)
              result = irIfThenElse(
                type = irBuiltIns.unitType,
                condition = irEqualsNull(irGet(exceptionVar)),
                thenPart = irSet(exceptionVar, irGet(catchParam)),
                elsePart = irCall(addSuppressedMethod).apply {
                  dispatchReceiver = irGet(exceptionVar)
                  arguments[1] = irGet(catchParam)
                },
              ),
            ),
          ),
          finallyExpression = null,
        ),
      )
    }

    // if ($closeException != null) throw $closeException
    result.add(
      irIfThen(
        type = irBuiltIns.unitType,
        condition = irNotEquals(irGet(exceptionVar), irNull()),
        thenPart = buildThrow(
          nothingType = irBuiltIns.nothingType,
          exception = irGet(exceptionVar),
        ),
      ),
    )

    return result
  }
}
