package kraii.ir

import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.visitors.acceptChildrenVoid

/**
 * Entry point for kraii's IR generation phase. Orchestrates three passes:
 *
 * 1. **Constructor exception safety** — Wraps property initializers in
 *    try-catch so that if a later @Scoped property's initializer throws, all
 *    previously initialized @Scoped properties are closed. Must run first
 *    because it modifies initializer expressions that later passes don't touch.
 *
 * 2. **Close method body generation** — Fills in the close() method body
 *    (generated by the FIR phase or user-defined) with code that closes all
 *    @Scoped properties in reverse declaration order. Must run after the
 *    constructor pass because it operates on close() methods, not initializers.
 *
 * 3. **Local variable close insertion** — Wraps statements after @Scoped local
 *    variables in try-finally blocks.
 */
class KraiiIrGenerationExtension : IrGenerationExtension {

  override fun generate(
    moduleFragment: IrModuleFragment,
    pluginContext: IrPluginContext,
  ) {
    moduleFragment.acceptChildrenVoid(
      visitor = KraiiConstructorExceptionSafetyTransformer(pluginContext),
    )
    moduleFragment.acceptChildrenVoid(
      visitor = KraiiCloseMethodBodyGenerator(pluginContext),
    )
    moduleFragment.transform(
      transformer = KraiiLocalVariableCloseInserter(pluginContext),
      data = null,
    )
  }
}
